set_property PACKAGE_PIN Y18 [get_ports clk_i]
set_property PACKAGE_PIN R1 [get_ports rst_i]

set_property PACKAGE_PIN C19 [get_ports led_ena[0]]
set_property PACKAGE_PIN E19 [get_ports led_ena[1]]
set_property PACKAGE_PIN D19 [get_ports led_ena[2]]
set_property PACKAGE_PIN F18 [get_ports led_ena[3]]
set_property PACKAGE_PIN E18 [get_ports led_ena[4]]
set_property PACKAGE_PIN B20 [get_ports led_ena[5]]
set_property PACKAGE_PIN A20 [get_ports led_ena[6]]
set_property PACKAGE_PIN A18 [get_ports led_ena[7]]

set_property PACKAGE_PIN F15 [get_ports led[7]]
set_property PACKAGE_PIN F13 [get_ports led[6]]
set_property PACKAGE_PIN F14 [get_ports led[5]]
set_property PACKAGE_PIN F16 [get_ports led[4]]
set_property PACKAGE_PIN E17 [get_ports led[3]]
set_property PACKAGE_PIN C14 [get_ports led[2]]
set_property PACKAGE_PIN C15 [get_ports led[1]]
set_property PACKAGE_PIN E13 [get_ports led[0]]



set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ena[7]]

set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]